title: "Attitudes towards Open Science and Data Sharing: Global Data"
description: "This dataset compiles quantitative data from international surveys (2018-2024) on attitudes of academic researchers towards open science and data shar"
author: "Juan Moisés de la Serna Tuya"
url: "https://juanmoisesd.github.io"
baseurl: "/attitudes-towards-open-science-and-data-sharing-global-dataset-of-researcher-sur"
